spring.application.name=e-com
spring.datasource.url=jdbc:mysql://localhost:3306/e_com
spring.datasource.username= root
spring.datasource.password= rohan@18
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
